# UVData configuration for pyuvdata
# This should only include values that aren't derived from data shape
# https://pyuvdata.readthedocs.io/en/latest/uvdata.html#required
history: Created from aavs_uv config/aavs2/uv_config.yaml
instrument: aavs2
telescope_name: aavs2
telescope_ECEF_X: -2559301.90974769
telescope_ECEF_Y: 5095070.36573217
telescope_ECEF_Z: -2848888.27966852
channel_width: 925926.0             # Hz 32/27 oversample
channel_spacing: 781250.0           # Hz - oversampled so spacing is smaller than width
antenna_locations_file: antenna_locations.txt
baseline_order_file: baseline_order.txt
polarization_type: linear_crossed  # stokes, circular, linear (XX, YY, XY, YX) or linear_crossed (XX, XY, YX, YY)
vis_units: uncalib
# PyUVData specific keywords
future_array_shapes: False
flex_spw: False
Nspws: 1
Nphase: 1