# UVX configuration file
history: Created with generate_uv_config_from_aa1_coordinates_csv()
instrument: S10-6
telescope_name: S10-6
telescope_ECEF_X: -2557860.492139279
telescope_ECEF_Y: 5087190.859247489
telescope_ECEF_Z: -2864840.6273791404
channel_spacing: 781250.0           # Channel spacing in Hz
channel_width: 925926.0             # 781250 Hz * 32/27 oversampling gives channel width
antenna_locations_file: antenna_locations.txt
baseline_order_file: baseline_order.txt
polarization_type: linear_crossed  # stokes, circular, linear (XX, YY, XY, YX) or linear_crossed (XX, XY, YX, YY)
vis_units: uncalib
# PyUVData specific keywords
future_array_shapes: False
flex_spw: False
Nspws: 1
Nphase: 1
