# UVX configuration file
history: Created with generate_uv_config_from_aa1_coordinates_csv()
instrument: S8-3
telescope_name: S8-3
telescope_ECEF_X: -2561317.9588135486
telescope_ECEF_Y: 5085866.670650514
telescope_ECEF_Z: -2864118.262670741
channel_spacing: 781250.0           # Channel spacing in Hz
channel_width: 925926.0             # 781250 Hz * 32/27 oversampling gives channel width
antenna_locations_file: antenna_locations.txt
baseline_order_file: baseline_order.txt
polarization_type: linear_crossed  # stokes, circular, linear (XX, YY, XY, YX) or linear_crossed (XX, XY, YX, YY)
vis_units: uncalib
# PyUVData specific keywords
future_array_shapes: False
flex_spw: False
Nspws: 1
Nphase: 1
