# UVData configuration for pyuvdata
# This should only include values that aren't derived from data shape
# https://pyuvdata.readthedocs.io/en/latest/uvdata.html#required
history: Created from ska_ost_low_uv config/eda2/uv_config.yaml
instrument: eda2
telescope_name: eda2
# From https://gitlab.com/ska-telescope/mccs/ska-low-mccs/-/blob/main/tmdata/instrument/mccs-configuration/station_export_w2.json?ref_type=heads
# lon = 116.672437792380549,
# lat = -26.704756537044446
# This does NOT include ellipsoidal_height, so using value from AAVS3: 359.495
# Calculated using astropy.coordinates.EarthLocation.from_geodetic()
# <EarthLocation (-2559558.89934823, 5095221.08110283, -2849191.20430937) m>
telescope_ECEF_X: -2559558.89934823
telescope_ECEF_Y:  5095221.08110283
telescope_ECEF_Z: -2849191.20430937
channel_width: 925926.0             # Hz - 32/27 oversample
channel_spacing: 781250.0           # Hz - oversampled so spacing is smaller than width
antenna_locations_file: antenna_locations.txt
baseline_order_file: baseline_order.txt
polarization_type: linear_crossed  # stokes, circular, linear (XX, YY, XY, YX) or linear_crossed (XX, XY, YX, YY)
receptor_angle: 0                  # clockwise rotation angle in degrees away from N-E
vis_units: uncalib
